# Default values for omar-config-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

appName: omar-config-server

global:
  dockerRepository: nexus-docker-private-group.ossim.io
  imagePullSecret:
    registry: null
    username: null
    password: null
  springConfigmapName: spring-config

  createImagePullSecret: true
  useImagePullSecret: true


# These variables can be overridden because of the use of the 'pluck' function:
# - createIngress
# - useTls
# - useTlsClientAuth
# - createImagePullSecret
# - createHpa
# - createPVs
# - useSpringConfigServer

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 15m
    memory: 500Mi
    
image:
  name: omar-config-server
  tag: dev
  pullPolicy: Always

internalPort: 8888
externalPort: 8888

livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 3


readinessProbe:
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
  path: /omar-config-server/actuator/health


terminationGracePeriodSeconds: 30

envVars:
  GIT_USER_NAME: 
  GIT_PASSWORD: 
  SPRING_PROFILES_ACTIVE: native

configmaps: {}

extraVolumes: []

extraVolumeMounts: []

extraInitContainers: []

sideCars: []
