# Default values for omar-config-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

fullnameOverride: omar-config-server

global:

  image:
    pullSecrets: []
  springConfigmapName: spring-config

  image:
    registry: ""
    pullPolicy: ""
    pullSecrets: []

  deployment:
    annotations: {}

  serviceAccount:
    enabled: false
    annotations: {}
    # name:

  envVars: {}
  envFrom: []
  nodeSelector: {}
  affinity: {}
  tolerations: []

# These variables can be overridden because of the use of the 'pluck' function:
# - createIngress
# - useTls
# - useTlsClientAuth
# - createImagePullSecret
# - createHpa
# - createPVs
# - useSpringConfigServer

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 15m
    memory: 500Mi

image:
  name: omar-config-server
  tag: null
  pullPolicy: ""

internalPort: 8888
externalPort: 8888

livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 3


readinessProbe:
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
  path: /omar-config-server/actuator/health


terminationGracePeriodSeconds: 30

envVars:
  GIT_USER_NAME:
  GIT_PASSWORD:
  SPRING_PROFILES_ACTIVE: native

configmaps: {}

extraVolumes: []

extraVolumeMounts: []

extraInitContainers: []

sideCars: []

deployment:
  annotations: {}

envFrom: []
nodeSelector: {}
affinity: {}
tolerations: []

serviceAccount:
  # Specifies whether a service account should be created
  enabled: null
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and enabled is true, a name is generated using the fullname template
  # name:
