apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-config-server
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-config-server
  uid: dcaaf236-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '8862999'
  generation: 173
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-config-server
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-config-server:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-config-server@sha256:f2751d2f71ff310f8fa2ae047b2c8c94478924be88d81550ee6e2177231f5697
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-config-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-config-server
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: omar-config-server
          image: >-
            172.30.181.173:5000/o2/omar-config-server@sha256:f2751d2f71ff310f8fa2ae047b2c8c94478924be88d81550ee6e2177231f5697
          ports:
            - containerPort: 8888
              protocol: TCP
          env:
            - name: GIT_USER_NAME
              value: ossimlabs-minion
            - name: GIT_PASSWORD
              value: <PASSWORD>
            - name: SPRING_PROFILES_ACTIVE
              value: remote
          resources: {}
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 160
  observedGeneration: 173
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-config-server:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-11-26T00:27:30Z'
      lastTransitionTime: '2017-11-26T00:27:30Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-11-30T12:31:26Z'
      lastTransitionTime: '2017-11-30T12:31:24Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-config-server-160" successfully rolled out
  readyReplicas: 1
